"""empty message

Revision ID: cbdd01fcb196
Revises: 11989d51e063
Create Date: 2025-11-24 01:11:31.615408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbdd01fcb196'
down_revision = '11989d51e063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('home_world',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('home_world',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
